# Generated by Django 5.1 on 2024-08-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='dni',
            new_name='numDoc',
        ),
    ]
