# Generated by Django 5.1 on 2024-08-19 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_alumno_options_alter_alumno_table_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos')),
            ],
            options={
                'unique_together': {('alumno', 'curso')},
            },
        ),
    ]
